#!/bin/bash

set -o errexit

if [ -z "${IMAGE}" ]; then
  printf "ERROR: The variable \$IMAGE should be set in the environment\n\n" 2>&1
  exit 1
fi

if [ -z "${TASK}" ]; then
  printf "ERROR: The variable \$TASK should be set in the environment\n\n" 2>&1
  exit 1
fi

#ensure that docker runs
if P=$(pgrep docker)
then
    echo "docker is running, PID is $P"
else
    sudo service docker start
    until info=$(docker info 2> /dev/null)
    do
       sleep 1
    done
fi

if [ -d "/build" ]; then
  docker build -t ${IMAGE} /build
fi

bundle exec cucumber
