#!/bin/bash

set -o errexit

if [ -z "${IMAGE}" ]; then
  printf "ERROR: The variable \$IMAGE should be set in the environment\n\n" 2>&1
  exit 1
fi

if [ -d "/build" ]; then
  docker build -t ${IMAGE} /build
fi

bundle exec cucumber
